### ISSUE TITLE
Patient-Bed Assignment

### ISSUE THREAD

**Issue by use-to** [helpwave/design#2]
Depends on https://github.com/helpwave/web/issues/348

**Comment by aegis301** [comment]
Users should be able to assign a patient to a bed and should be able to reassign them quickly and easily.

While we aim for a drag and drop solution, for now patients assignment and reassignment will be handled via accessing the patients name with an option to relocate or to assign to a bed.

![Bildschirm_foto 2023-04-13 um 20 23 19](https://github.com/helpwave/design/assets/57251443/166e2513-882f-435f-8b7c-ab79ff7cad0f)

**Comment by jonas-ester** [comment]
When a ward is selected and no bed ist selected we will use the blank space on the right hand side to show a list of all patient assigned to that ward. The list is split into three sections: active, unassigned, discharged

Clicking on a patient opens the patient detail section on the right, just like selecting a bed.

When a bed gets selected the right section shows the bed details as usual. 

**[View in Figma](https://www.figma.com/file/4oxQRRLaNQ1TdBVhI0CZ4B/helpwave-frontend?type=design&node-id=1740%3A2827&mode=design&t=qXOmyKbuzwZES13x-1)** 

![image](https://github.com/helpwave/design/assets/81472060/d5416480-8d08-4fef-b688-99a6c81a0287)

**Comment by jonas-ester** [comment]
The patient detail page needs the following modifications:

- Clicking outside of any bed tiles in the left section closes the patient detail section and shows the patient list instead
- Adding a close button to the top of the patient detail section
- Adding two additional drop down controls to assign a room and a bed
- The room drop down needs the option "unassigned" when that is selected the bed drop down is inactive
- An additional button to unassigned the patient

<img width="339" alt="Bildschirmfoto 2023-07-01 um 14 20 01" src="https://github.com/helpwave/design/assets/81472060/5c3b7f9c-095b-473e-8433-777bb00b971e">

**Comment by MaxSchaefer** [comment]
Thanks, great!
