### ISSUE TITLE
Due-Date-Available-Indicator and Avatar-Icon

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/design#8]
### Describe the feature

We need a mock for displaying the Due-Date-Available-Indicator and Avatar-Icon on a task card. For the Due-Date-Available-Indicator, there is already a mock available.

The following icons are already on the task
- Public-Private-Indicator (Lock-Icon)
- Progress-Indicator
We want to add two more
- Avatar-Icon (The avatar of the assigned user)
  - Fallback for multiple users to the avatar stack
- Due-Date-Available-Indicator (If a due date is set)
  - There is already a mock available, see second screenshot of figma

![Bildschirmfoto 2023-10-09 um 10 53 11 PM](https://github.com/helpwave/design/assets/40192999/baa82ce0-51a8-4352-bf22-cb3bad2e721a)
![Bildschirmfoto 2023-10-09 um 10 55 42 PM](https://github.com/helpwave/design/assets/40192999/b8729d33-fa78-4eeb-aaa0-2c5281b75d53)

### Why is this feature needed?

We need a mock for displaying the Due-Date-Available-Indicator and Avatar-Icon. For the Due-Date-Available-Indicator, there is already a mock available.

**Comment by jonas-ester** [comment]
Layout suggestion:

<img width="246" alt="Bildschirmfoto 2023-10-15 um 21 07 01" src="https://github.com/helpwave/design/assets/81472060/d5838ed5-456c-4d53-a393-ec4c7b68203a">
